//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityCv
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILGILER
    {
        public byte ID { get; set; }
        public string ADSOYAD { get; set; }
        public string EGITIM { get; set; }
        public string STAJDENEYIMLERI { get; set; }
    }
}
